#!/bin/bash

REPO_NAME="misak-repo"
REPO_PATH="x86_64"
current=$(pwd)
AurHelper=yay
if [ ! -d ${current}/aur-hash ];then mkdir ${current}/aur-hash;fi
if [ ! -d ${current}/build ];then mkdir ${current}/build;fi

# e.g. IgnorePkgs=('pkg1' 'pkg2')
IgnorePkgs=()

IgnorePkg=($(sort <<<"${IgnorePkg[*]}"));

AurPkgs=('cura-bin'
	 'protobuf-git'
	 'ffmpeg-cuda'
	 'google-chrome'
	)

GitPkgs=('crow-translate-git'
	)

# Regular Colors
Black="\e[0;30m"
Red="\e[0;31m"
Green="\e[0;32m"
Yellow="\e[0;33m"
Blue="\e[0;34m"
Purple="\e[0;35m"
Cyan="\e[0;36m"
White="\e[0;37m"

clear_term() {
	clear -x
}

msg() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    GREEN="${BOLD}\e[1;32m"
      local mesg=$1; shift
      printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
 }

info() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    BLUE="${BOLD}\e[1;34m"
      local mesg=$(echo "$1" | sed "s/%//g"); shift
      printf "${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
 }

info_red() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    BLUE="${BOLD}${Red}"
      local mesg=$(echo "$1" | sed -i "s/%//g"); shift
      printf "${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
 }

init_lfs() {
	cd ${current}
	git lfs install --local
	git lfs pull
	echo "lfs is initialized" > ${current}/.initialized
	if [ ! "$(git config get pull.rebase)" == "true" ];then
		git config pull.rebase true
	fi
}

update_repo() {
	local files=$1
	local temp
	
	repo-add -n "${REPO_PATH}/${REPO_NAME}.db.tar.gz" "$REPO_PATH/$files"
}

read_package_name() {
	local package=$1
	if [[ -z $package ]] || [[ ! -f $package ]]; then
		echo "read_package_name called without a valid argument. Aborting"
		exit 1
	fi

	pacman -Qqp "$package"
}

full_repo_update() {
	for package in "$REPO_PATH"/*.pkg.tar*; do
		packagelist="$packagelist $(read_package_name "$package")"
	done
	packagelist=$(echo "$packagelist" | tr ' ' '\n' | uniq)

	for package_name in $packagelist; do
		current=$(echo "${REPO_PATH}/${package_name}"*.pkg.tar* | tr ' ' '\n' | xargs ls -l --time-style=+%s | sort -k 6 | awk '{ print $7 }' | tail -n 1)
		update_repo "${current##*/}"
	done

}

if [ ! -f ${current}/.initialized ] || [ "$1" == "init" ];then
	init_lfs
fi

build_package() {
	if [ -f ${current}/patch/${1}.patch ];then
		if [ -f ${current}/build/${1} ];then rm -rf ${current}/build/${1};fi
		cd ${current}/build
		git clone https://aur.archlinux.org/${1}.git
		cd ${current}/build/${1}
		patch -Np1 -i ${current}/patch/${1}.patch
	elif [ ! -f ${current}/build/${1} ];then
		cd ${current}/build
		git clone https://aur.archlinux.org/${1}.git
	fi
	cd ${current}/build/${1}
	git pull
	makepkg -Ccs
	if [ $? -ne 0 ];then
		info_red "Nepodařilo se zkompilovat balíček: ${1}"
		exit
	fi
	mv *.pkg.tar* ${current}/x86_64
	echo "$(git log -n 1 --pretty=format:"%H")" > ${current}/aur-hash/${1}
	
}

test_update_package() {
	# get changed scripts
	aur=$(${AurHelper} -Quaq)

	# setup arrays
	IFS=$'\n' ignored=("$(sort <<<"${IgnorePkgs[*]}")"); unset IFS
	IFS=$'\n' changed=("$(sort <<<"${aur[*]}")"); unset IFS

	# create a filtered array
	filtered=$(comm -13 <(printf "%s\n" "${ignored[@]}") <(printf "%s\n" "${changed[@]}"))

	# create the notification
	notification=$(for f in "${filtered[@]}"; do echo "${f}"; done)

	# display notification if the filtered array is not empty
	if  [[ -n "${notification}" ]]; then
	        echo "${notification}"
	fi
}

get_commit_hash() {
	git_commit_hash=$(git ls-remote https://aur.archlinux.org/$1.git | grep refs/heads/master | cut -f 1)
	if [ -f ${current}/aur-hash/$1 ];then
		git_commit_hash_saved=$(cat ${current}/aur-hash/$1)
		if [ "${git_commit_hash}" == "${git_commit_hash_saved}" ];then
			echo "true"
		else
			echo "false"
		fi
	else
		echo "false"
	fi
}

check_change_aur_package() {
	
	for package in "${AurPkgs[@]}"; do
		if [ "$(get_commit_hash ${package})" == "false" ];then
			build_package ${package}
		fi
#		echo "${package}"
		#packagelist="$packagelist $(read_package_name "$package")"
	done

}

git pull
#check_change_aur_package
#test_update_package
#exit
#wait
full_repo_update
wait
rm $REPO_PATH/misak-repo.files
cp $REPO_PATH/misak-repo.files.tar.gz $REPO_PATH/misak-repo.files
rm $REPO_PATH/misak-repo.db
cp $REPO_PATH/misak-repo.db.tar.gz $REPO_PATH/misak-repo.db
wait
git add .
git commit -m "Add package."
git push
wait
